/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopoo;

import static proyectopoo.Menu.t;
import static proyectopoo.Menu.r;
/**
 *
 * @author irvin
 */
public class Configuracion extends javax.swing.JFrame {
    
    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        canciones = new javax.swing.JComboBox<>();
        colorestablero = new javax.swing.JComboBox<>();
        play1 = new javax.swing.JButton();
        volumen = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuracion");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setText("Configuración");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 26, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jButton1.setText("Atras");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 50, -1));

        canciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dragon Ball", "Merengue", "Chopin", "Doom" }));
        canciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancionesActionPerformed(evt);
            }
        });
        getContentPane().add(canciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 160, -1));

        colorestablero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azul", "Verde", "Rosa", "Morado" }));
        colorestablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorestableroActionPerformed(evt);
            }
        });
        getContentPane().add(colorestablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, -1));

        play1.setText("||►♪");
        play1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play1ActionPerformed(evt);
            }
        });
        getContentPane().add(play1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 70, -1));

        volumen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                volumenMouseDragged(evt);
            }
        });
        volumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volumenMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                volumenMouseReleased(evt);
            }
        });
        getContentPane().add(volumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/fondo_resize.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/icono.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 310, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        dispose();
        m.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void colorestableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorestableroActionPerformed
        // TODO add your handling code here:
        
        t.tb1.t.setColor(colorestablero.getItemAt(colorestablero.getSelectedIndex()));
        t.tb2.t.setColor(colorestablero.getItemAt(colorestablero.getSelectedIndex()));
        t.tb3.t.setColor(colorestablero.getItemAt(colorestablero.getSelectedIndex()));
        t.tb4.t.setColor(colorestablero.getItemAt(colorestablero.getSelectedIndex()));
        t.tb5.t.setColor(colorestablero.getItemAt(colorestablero.getSelectedIndex()));
        t.tm1.t.setColor(colorestablero.getItemAt(colorestablero.getSelectedIndex()));
        t.tm2.t.setColor(colorestablero.getItemAt(colorestablero.getSelectedIndex()));
        t.tm3.t.setColor(colorestablero.getItemAt(colorestablero.getSelectedIndex()));
        t.tm4.t.setColor(colorestablero.getItemAt(colorestablero.getSelectedIndex()));
        t.tm5.t.setColor(colorestablero.getItemAt(colorestablero.getSelectedIndex()));
        t.ta1.t.setColor(colorestablero.getItemAt(colorestablero.getSelectedIndex()));
        t.ta2.t.setColor(colorestablero.getItemAt(colorestablero.getSelectedIndex()));
        t.ta3.t.setColor(colorestablero.getItemAt(colorestablero.getSelectedIndex()));
        t.ta4.t.setColor(colorestablero.getItemAt(colorestablero.getSelectedIndex()));
    }//GEN-LAST:event_colorestableroActionPerformed

    private void cancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancionesActionPerformed
        // TODO add your handling code here:
        r.setCancion(canciones.getItemAt(canciones.getSelectedIndex()));
        System.out.println("La cancion actual es:"+r.seleccion);
        
    }//GEN-LAST:event_cancionesActionPerformed

    private void play1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play1ActionPerformed
        // TODO add your handling code here:
        if(!r.isMusic){
            if(r.seleccion.equals("Dragon Ball")) r.mp_1.play();
            if(r.seleccion.equals("Chopin")) r.mp_2.play();
            if(r.seleccion.equals("Merengue")) r.mp_3.play();
            if(r.seleccion.equals("Doom")) r.mp_4.play();   
            r.isMusic = true;
            
        }
        else{
            if(r.seleccion.equals("Dragon Ball")) r.mp_1.stop();
            if(r.seleccion.equals("Chopin")) r.mp_2.stop();
            if(r.seleccion.equals("Merengue")) r.mp_3.stop();
            if(r.seleccion.equals("Doom")) r.mp_4.stop(); 
            r.isMusic = false;
        }

    }//GEN-LAST:event_play1ActionPerformed

    private void volumenMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volumenMouseDragged
        if(r.seleccion.equals("Dragon Ball")) r.mp_1.setVolume((double)evt.getX()/100);
        if(r.seleccion.equals("Chopin")) r.mp_2.setVolume((double)evt.getX()/100);
        if(r.seleccion.equals("Merengue")) r.mp_3.setVolume((double)evt.getX()/100);
        if(r.seleccion.equals("Doom")) r.mp_4.setVolume((double)evt.getX()/100);; 
    }//GEN-LAST:event_volumenMouseDragged

    private void volumenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volumenMouseClicked

    }//GEN-LAST:event_volumenMouseClicked

    private void volumenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volumenMouseReleased

    }//GEN-LAST:event_volumenMouseReleased

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/icono_reflejo.png")));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/icono.png")));
    }//GEN-LAST:event_jLabel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> canciones;
    private javax.swing.JComboBox<String> colorestablero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton play1;
    private javax.swing.JSlider volumen;
    // End of variables declaration//GEN-END:variables
}
