/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopoo;
import java.util.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static proyectopoo.PantallaPrincipal.u;

/**
 *
 * @author irvin
 */
public class Menu extends javax.swing.JFrame {
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
    public static Repertorio_Musica r = new Repertorio_Musica();
    public static Tacticas t = new Tacticas();


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        datos_usuario = new javax.swing.JLabel();
        btnConfiguracion = new javax.swing.JButton();
        tb1 = new javax.swing.JButton();
        tb2 = new javax.swing.JButton();
        tb3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tb4 = new javax.swing.JButton();
        tb5 = new javax.swing.JButton();
        tm1 = new javax.swing.JButton();
        tm2 = new javax.swing.JButton();
        tm3 = new javax.swing.JButton();
        tm4 = new javax.swing.JButton();
        tm5 = new javax.swing.JButton();
        ta1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ta2 = new javax.swing.JButton();
        ta3 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ta4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        datos_usuario1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu de tacticas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("<html><font color = 'white'><b>Básicas</b></font></html>");
        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 14));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 90, 50));

        datos_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datos_usuarioMouseEntered(evt);
            }
        });
        datos_usuario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datos_usuarioPropertyChange(evt);
            }
        });
        getContentPane().add(datos_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 300, 40));
        u.setTitulo();
        datos_usuario.setText("<html><font color='white'> Bienvenido:"+u.getNombre()+" ELO: "+u.getElo()+".Titulo:"+u.getTitulo()+"</font></html>");

        btnConfiguracion.setText("Configuración");
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        tb1.setText("1");
        tb1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tb1MouseMoved(evt);
            }
        });
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb1MouseExited(evt);
            }
        });
        tb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb1ActionPerformed(evt);
            }
        });
        getContentPane().add(tb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 50, -1));

        tb2.setText("2");
        tb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb2MouseExited(evt);
            }
        });
        tb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb2ActionPerformed(evt);
            }
        });
        getContentPane().add(tb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 50, -1));

        tb3.setText("3");
        tb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb3MouseExited(evt);
            }
        });
        tb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb3ActionPerformed(evt);
            }
        });
        getContentPane().add(tb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 50, -1));

        jLabel5.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel5.setText("<html><font color='white'>Bienvenido al programa de tacticas de ajedrez!</font></html>");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 520, 30));

        tb4.setText("4");
        tb4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb4MouseExited(evt);
            }
        });
        tb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb4ActionPerformed(evt);
            }
        });
        getContentPane().add(tb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 50, -1));

        tb5.setText("5");
        tb5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb5MouseExited(evt);
            }
        });
        tb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb5ActionPerformed(evt);
            }
        });
        getContentPane().add(tb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 50, -1));

        tm1.setText("1");
        tm1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tm1MouseMoved(evt);
            }
        });
        tm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tm1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tm1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tm1MousePressed(evt);
            }
        });
        tm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tm1ActionPerformed(evt);
            }
        });
        getContentPane().add(tm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 50, -1));

        tm2.setText("2");
        tm2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tm2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tm2MouseExited(evt);
            }
        });
        tm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tm2ActionPerformed(evt);
            }
        });
        getContentPane().add(tm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 50, -1));

        tm3.setText("3");
        tm3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tm3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tm3MouseExited(evt);
            }
        });
        tm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tm3ActionPerformed(evt);
            }
        });
        getContentPane().add(tm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 50, -1));

        tm4.setText("4");
        tm4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tm4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tm4MouseExited(evt);
            }
        });
        tm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tm4ActionPerformed(evt);
            }
        });
        getContentPane().add(tm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 50, -1));

        tm5.setText("5");
        tm5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tm5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tm5MouseExited(evt);
            }
        });
        tm5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tm5ActionPerformed(evt);
            }
        });
        getContentPane().add(tm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 50, -1));

        ta1.setText("1");
        ta1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ta1MouseMoved(evt);
            }
        });
        ta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ta1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ta1MouseExited(evt);
            }
        });
        ta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ta1ActionPerformed(evt);
            }
        });
        getContentPane().add(ta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 50, -1));

        jLabel6.setText("<html><font color = 'white'><b>Avanzado</b></font></html>");
        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 1, 14));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 190, 40));

        ta2.setText("2");
        ta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ta2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ta2MouseExited(evt);
            }
        });
        ta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ta2ActionPerformed(evt);
            }
        });
        getContentPane().add(ta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 50, -1));

        ta3.setText("3");
        ta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ta3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ta3MouseExited(evt);
            }
        });
        ta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ta3ActionPerformed(evt);
            }
        });
        getContentPane().add(ta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 50, -1));

        jButton3.setText("Progreso!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, -1, -1));

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jLabel4.setText("<html><font color = 'white'><b>Medio</b></font></html>");
        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 14));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 120, 30));

        ta4.setText("4");
        ta4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ta4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ta4MouseExited(evt);
            }
        });
        ta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ta4ActionPerformed(evt);
            }
        });
        getContentPane().add(ta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 50, -1));

        jButton1.setText("Usuarios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/icono.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 310, 410));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/fondo_resize.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 490));

        datos_usuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datos_usuario1MouseEntered(evt);
            }
        });
        datos_usuario1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datos_usuario1PropertyChange(evt);
            }
        });
        getContentPane().add(datos_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 300, 40));
        u.setTitulo();
        datos_usuario.setText("<html><font color='white'> Bienvenido:"+u.getNombre()+" ELO: "+u.getElo()+".Titulo:"+u.getTitulo()+"</font></html>");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        // TODO add your handling code here:
        Configuracion c = new Configuracion();
        dispose();
        c.setVisible(true);
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void tb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb1ActionPerformed
        
        t.tb1.t.intentos = 0; t.tb1.t.pieza_activa = null; t.tb1.t.victoria = false; 
        t.tb1.t.initGrid();
        t.tb1.t.drawBoard();
        t.tb1.t.iniciarTiempo();
        t.tb1.run();
        
    }//GEN-LAST:event_tb1ActionPerformed

    private void tb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb3ActionPerformed
        // TODO add your handling code here:
        t.tb3.t.drawBoard();
        t.tb3.t.intentos = 0; t.tb3.t.pieza_activa = null; t.tb3.t.victoria = false; 
        t.tb3.t.iniciarTiempo();
        t.tb3.run();

    }//GEN-LAST:event_tb3ActionPerformed

    private void tb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb4ActionPerformed
        // TODO add your handling code here:
        
        t.tb4.t.intentos = 0; t.tb4.t.pieza_activa = null; t.tb4.t.victoria = false; 
        t.tb4.t.initGrid();
        t.tb4.t.drawBoard();
        t.tb4.t.iniciarTiempo();
        t.tb4.run();
    }//GEN-LAST:event_tb4ActionPerformed

    private void tb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb5ActionPerformed
        // TODO add your handling code here:
        t.tb5.t.intentos = 0; t.tb5.t.pieza_activa = null; t.tb5.t.victoria = false; 
        t.tb5.t.initGrid();
        t.tb5.t.drawBoard();t.tb5.t.iniciarTiempo();
        t.tb5.run();
    }//GEN-LAST:event_tb5ActionPerformed

    private void tb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb2ActionPerformed
        // TODO add your handling code here:
        t.tb2.t.drawBoard();
        t.tb2.t.intentos = 0; t.tb2.t.pieza_activa = null; t.tb2.t.victoria = false; 
        t.tb2.t.iniciarTiempo();
        t.tb2.run();
    }//GEN-LAST:event_tb2ActionPerformed

    private void datos_usuarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datos_usuarioPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_datos_usuarioPropertyChange

    private void datos_usuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datos_usuarioMouseEntered
        // TODO add your handling code here:
        u.setTitulo();
        datos_usuario.setText("<html><font color='white'> Bienvenido:"+u.getNombre()+" ELO: "+u.getElo()+".Titulo:"+u.getTitulo()+"</font></html>");

    }//GEN-LAST:event_datos_usuarioMouseEntered
    JPanel p_tb1 = new JPanel();
    JFrame j_tb1 = new JFrame();
    JPanel p_tb2 = new JPanel();
    JFrame j_tb2 = new JFrame();
    JPanel p_tb3 = new JPanel();
    JFrame j_tb3 = new JFrame();
    JPanel p_tb4 = new JPanel();
    JFrame j_tb4 = new JFrame();
    JPanel p_tb5 = new JPanel();
    JFrame j_tb5 = new JFrame();
    
    JPanel p_tm1 = new JPanel();
    JFrame j_tm1 = new JFrame();
    JPanel p_tm2 = new JPanel();
    JFrame j_tm2 = new JFrame();
    JPanel p_tm3 = new JPanel();
    JFrame j_tm3 = new JFrame();
    JPanel p_tm4 = new JPanel();
    JFrame j_tm4 = new JFrame();
    JPanel p_tm5 = new JPanel();
    JFrame j_tm5 = new JFrame();   
    
    JPanel p_ta1 = new JPanel();
    JFrame j_ta1 = new JFrame();
    JPanel p_ta2 = new JPanel();
    JFrame j_ta2 = new JFrame();
    JPanel p_ta3 = new JPanel();
    JFrame j_ta3 = new JFrame();
    JPanel p_ta4 = new JPanel();
    JFrame j_ta4 = new JFrame();
    JPanel p_ta5 = new JPanel();
    JFrame j_ta5 = new JFrame();    
    JLabel star_1 = new JLabel();
    JLabel star_2 = new JLabel();      
    JLabel star_3 = new JLabel();
    Icon star1_icon = new ImageIcon(this.getClass().getResource("star1.gif"));
    
    
    private void tb1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseMoved


    }//GEN-LAST:event_tb1MouseMoved

    private void tb1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseExited
        // TODO add your handling code here:
        j_tb1.setVisible(false);
    }//GEN-LAST:event_tb1MouseExited

    private void tb2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb2MouseEntered
        // TODO add your handling code here:
        System.out.println(t.tb2.t.estrellas);

        if(t.tb2.t.estrellas == 0){
            p_tb2.removeAll();
            JLabel l = new JLabel("Sin estrellas!");
            p_tb2.add(l);
        }
        if(t.tb2.t.estrellas == 3){
            p_tb2.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            star_3.setIcon(star1_icon);
            p_tb2.add(star_1); p_tb2.add(star_2); p_tb2.add(star_3);
        }
        if(t.tb2.t.estrellas == 2){
            p_tb2.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            p_tb2.add(star_1); p_tb2.add(star_2); 
        }
        if(t.tb2.t.estrellas == 1){
            p_tb2.removeAll();
            star_1.setIcon(star1_icon);
            p_tb2.add(star_1);
        }
        j_tb2.setTitle("Estrellas TB2");
        j_tb2.add(p_tb2);
        j_tb2.setBounds(340,200,100,100);
        j_tb2.setLocationRelativeTo(null);        j_tb2.setVisible(true);
    }//GEN-LAST:event_tb2MouseEntered

    private void tb2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb2MouseExited
        // TODO add your handling code here:
        j_tb2.setVisible(false);
        
    }//GEN-LAST:event_tb2MouseExited

    private void tm1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tm1MouseMoved

    private void tm1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm1MouseExited
        j_tm1.setVisible(false);
    }//GEN-LAST:event_tm1MouseExited

    private void tm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tm1ActionPerformed
        t.tm1.t.drawBoard();
        t.tm1.t.intentos = 0; t.tm1.t.pieza_activa = null; t.tm1.t.victoria = false;
        t.tm1.t.iniciarTiempo();
        t.tm1.run();
    }//GEN-LAST:event_tm1ActionPerformed

    private void tm2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm2MouseEntered


        if(t.tm2.t.estrellas == 0){
            p_tm2.removeAll();
            JLabel l = new JLabel("Sin estrellas!");
            p_tm2.add(l);
        }
        if(t.tm2.t.estrellas == 3){
            p_tm2.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            star_3.setIcon(star1_icon);
            p_tm2.add(star_1); p_tm2.add(star_2); p_tm2.add(star_3);
        }
        if(t.tm2.t.estrellas == 2){
            p_tm2.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            p_tm2.add(star_1); p_tm2.add(star_2); 
        }
        if(t.tm2.t.estrellas == 1){
            p_tm2.removeAll();
            star_1.setIcon(star1_icon);
            p_tm2.add(star_1);
        }
        j_tm2.setTitle("Estrellas TM2");
        j_tm2.add(p_tm2);
        j_tm2.setBounds(340,200,100,100);
        j_tm2.setLocationRelativeTo(null);        j_tm2.setVisible(true);
    }//GEN-LAST:event_tm2MouseEntered

    private void tm2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm2MouseExited
        j_tm2.setVisible(false);
    }//GEN-LAST:event_tm2MouseExited

    private void tm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tm2ActionPerformed
        t.tm1.t.drawBoard();
        t.tm1.t.intentos = 0; t.tm1.t.pieza_activa = null; t.tm1.t.victoria = false;t.tm2.t.iniciarTiempo();
        t.tm1.run();
    }//GEN-LAST:event_tm2ActionPerformed

    private void tm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tm3ActionPerformed
        t.tm3.t.drawBoard();
        t.tm3.t.intentos = 0; t.tm3.t.pieza_activa = null; t.tm3.t.victoria = false; 
        t.tm3.t.iniciarTiempo();
        t.tm3.run();
    }//GEN-LAST:event_tm3ActionPerformed

    private void tm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tm4ActionPerformed
        t.tm4.t.intentos = 0; t.tm4.t.pieza_activa = null; t.tm4.t.victoria = false; 
        t.tm4.t.initGrid();
        t.tm4.t.drawBoard();
        t.tm4.t.iniciarTiempo();
        t.tm4.run();
    }//GEN-LAST:event_tm4ActionPerformed

    private void tm5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tm5ActionPerformed
        t.tm5.t.drawBoard();
        t.tm5.t.intentos = 0; t.tm5.t.pieza_activa = null; t.tm5.t.victoria = false;t.tm5.t.iniciarTiempo();
        t.tm5.run();
    }//GEN-LAST:event_tm5ActionPerformed

    private void ta1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ta1MouseMoved

    private void ta1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta1MouseExited
        j_ta1.setVisible(false);
    }//GEN-LAST:event_ta1MouseExited

    private void ta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ta1ActionPerformed
        t.ta1.t.drawBoard();
        t.ta1.t.intentos = 0; t.ta1.t.pieza_activa = null; t.ta1.t.victoria = false;
        t.ta1.t.iniciarTiempo();
        t.ta1.run();
    }//GEN-LAST:event_ta1ActionPerformed

    private void ta2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta2MouseEntered

        if(t.ta2.t.estrellas == 0){
            p_ta2.removeAll();
            JLabel l = new JLabel("Sin estrellas!");
            p_ta2.add(l);
        }
        if(t.ta2.t.estrellas == 3){
            p_ta2.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            star_3.setIcon(star1_icon);
            p_ta2.add(star_1); p_ta2.add(star_2); p_ta2.add(star_3);
        }
        if(t.ta2.t.estrellas == 2){
            p_ta2.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            p_ta2.add(star_1); p_ta2.add(star_2); 
        }
        if(t.ta2.t.estrellas == 1){
            p_ta2.removeAll();
            star_1.setIcon(star1_icon);
            p_ta2.add(star_1);
        }
        j_ta2.setTitle("Estrellas TM2");
        j_ta2.add(p_ta2);
        j_ta2.setBounds(340,200,100,100);
        j_ta2.setLocationRelativeTo(null);        j_ta2.setVisible(true);
    }//GEN-LAST:event_ta2MouseEntered

    private void ta2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta2MouseExited
        j_ta2.setVisible(false);
    }//GEN-LAST:event_ta2MouseExited

    private void ta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ta2ActionPerformed
        t.ta2.t.drawBoard();
        t.ta2.t.intentos = 0; t.ta2.t.pieza_activa = null; t.ta2.t.victoria = false;
        t.ta2.t.iniciarTiempo();
        t.ta2.run();
    }//GEN-LAST:event_ta2ActionPerformed

    private void ta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ta3ActionPerformed
        t.ta3.t.drawBoard();
        t.ta3.t.intentos = 0; t.ta3.t.pieza_activa = null; t.ta3.t.victoria = false;
        t.ta3.t.iniciarTiempo();
        t.ta3.run();
    }//GEN-LAST:event_ta3ActionPerformed

    private void ta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ta4ActionPerformed
        t.ta4.t.initGrid();
        t.ta4.t.drawBoard();
        t.ta4.t.intentos = 0; t.ta4.t.pieza_activa = null; t.ta4.t.victoria = false;
        t.ta4.t.iniciarTiempo();
        t.ta4.run();
    }//GEN-LAST:event_ta4ActionPerformed

    private void tb1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseEntered


        if(t.tb1.t.estrellas == 0){
            p_tb1.removeAll();
            JLabel l = new JLabel("Sin estrellas!");
            p_tb1.add(l);
        }
        if(t.tb1.t.estrellas == 3){
            p_tb1.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            star_3.setIcon(star1_icon);
            p_tb1.add(star_1); p_tb1.add(star_2); p_tb1.add(star_3);
        }
        if(t.tb1.t.estrellas == 2){
            p_tb1.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            p_tb1.add(star_1); p_tb1.add(star_2); 
        }
        if(t.tb1.t.estrellas == 1){
            p_tb1.removeAll();
            star_1.setIcon(star1_icon);
            p_tb1.add(star_1);
        }
        j_tb1.setTitle("Estrellas TB1");
        j_tb1.add(p_tb1);
        j_tb1.setBounds(340,200,100,100);
        j_tb1.setLocationRelativeTo(null);        j_tb1.setVisible(true);
    }//GEN-LAST:event_tb1MouseEntered

    private void tb3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb3MouseEntered


        if(t.tb3.t.estrellas == 0){
            p_tb3.removeAll();
            JLabel l = new JLabel("Sin estrellas!");
            p_tb3.add(l);
        }
        if(t.tb3.t.estrellas == 3){
            p_tb3.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            star_3.setIcon(star1_icon);
            p_tb3.add(star_1); p_tb3.add(star_2); p_tb3.add(star_3);
        }
        if(t.tb3.t.estrellas == 2){
            p_tb3.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            p_tb3.add(star_1); p_tb3.add(star_2); 
        }
        if(t.tb3.t.estrellas == 1){
            p_tb3.removeAll();
            star_1.setIcon(star1_icon);
            p_tb3.add(star_1);
        }
        j_tb3.setTitle("Estrellas TB3");
        j_tb3.add(p_tb3);
        j_tb3.setBounds(340,200,100,100);
        j_tb3.setLocationRelativeTo(null);        j_tb3.setVisible(true);
    }//GEN-LAST:event_tb3MouseEntered

    private void tb3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb3MouseExited
        j_tb3.setVisible(false);
    }//GEN-LAST:event_tb3MouseExited

    private void tb4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb4MouseEntered


        if(t.tb4.t.estrellas == 0){
            p_tb4.removeAll();
            JLabel l = new JLabel("Sin estrellas!");
            p_tb4.add(l);
        }
        if(t.tb4.t.estrellas == 3){
            p_tb4.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            star_3.setIcon(star1_icon);
            p_tb4.add(star_1); p_tb4.add(star_2); p_tb4.add(star_3);
        }
        if(t.tb4.t.estrellas == 2){
            p_tb4.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            p_tb4.add(star_1); p_tb4.add(star_2); 
        }
        if(t.tb4.t.estrellas == 1){
            p_tb4.removeAll();
            star_1.setIcon(star1_icon);
            p_tb4.add(star_1);
        }
        j_tb4.setTitle("Estrellas TB4");
        j_tb4.add(p_tb4);
        j_tb4.setBounds(900,350,100,100);
        j_tb4.setVisible(true);
    }//GEN-LAST:event_tb4MouseEntered

    private void tb4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb4MouseExited
        j_tb4.setVisible(false);
    }//GEN-LAST:event_tb4MouseExited

    private void tb5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb5MouseEntered


        if(t.tb5.t.estrellas == 0){
            p_tb5.removeAll();
            JLabel l = new JLabel("Sin estrellas!");
            p_tb5.add(l);
        }
        if(t.tb5.t.estrellas == 3){
            p_tb5.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            star_3.setIcon(star1_icon);
            p_tb5.add(star_1); p_tb5.add(star_2); p_tb5.add(star_3);
        }
        if(t.tb5.t.estrellas == 2){
            p_tb3.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            p_tb5.add(star_1); p_tb5.add(star_2); 
        }
        if(t.tb5.t.estrellas == 1){
            p_tb5.removeAll();
            star_1.setIcon(star1_icon);
            p_tb5.add(star_1);
        }
        j_tb5.setTitle("Estrellas TB3");
        j_tb5.add(p_tb5);
        j_tb5.setBounds(900,350,100,100);
        j_tb5.setVisible(true);
    }//GEN-LAST:event_tb5MouseEntered

    private void tb5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb5MouseExited
        // TODO add your handling code here:
        j_tb5.setVisible(false);
    }//GEN-LAST:event_tb5MouseExited

    private void tb5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tb5MouseClicked

    private void tm1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm1MouseEntered


        if(t.tm1.t.estrellas == 0){
            p_tm1.removeAll();
            JLabel l = new JLabel("Sin estrellas!");
            p_tm1.add(l);
        }
        if(t.tm1.t.estrellas == 3){
            p_tm1.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            star_3.setIcon(star1_icon);
            p_tm1.add(star_1); p_tm1.add(star_2); p_tm1.add(star_3);
        }
        if(t.tm1.t.estrellas == 2){
            p_tm1.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            p_tm1.add(star_1); p_tm1.add(star_2); 
        }
        if(t.tm1.t.estrellas == 1){
            p_tm1.removeAll();
            star_1.setIcon(star1_icon);
            p_tm1.add(star_1);
        }
        j_tm1.setTitle("Estrellas TM1");
        j_tm1.add(p_tm1);
        j_tm1.setBounds(340,200,100,100);
        j_tm1.setLocationRelativeTo(null);        j_tm1.setVisible(true);
    }//GEN-LAST:event_tm1MouseEntered

    private void tm1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tm1MousePressed

    private void tm3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm3MouseExited
        j_tm3.setVisible(false);
    }//GEN-LAST:event_tm3MouseExited

    private void tm3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm3MouseEntered


        if(t.tm3.t.estrellas == 0){
            p_tm3.removeAll();
            JLabel l = new JLabel("Sin estrellas!");
            p_tm3.add(l);
        }
        if(t.tm3.t.estrellas == 3){
            p_tm3.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            star_3.setIcon(star1_icon);
            p_tm3.add(star_1); p_tm3.add(star_2); p_tm3.add(star_3);
        }
        if(t.tm3.t.estrellas == 2){
            p_tm3.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            p_tm3.add(star_1); p_tm3.add(star_2); 
        }
        if(t.tm3.t.estrellas == 1){
            p_tm3.removeAll();
            star_1.setIcon(star1_icon);
            p_tm3.add(star_1);
        }
        j_tm3.setTitle("Estrellas TM1");
        j_tm3.add(p_tm3);
        j_tm3.setBounds(340,200,100,100);
        j_tm3.setLocationRelativeTo(null);        j_tm3.setVisible(true);
    }//GEN-LAST:event_tm3MouseEntered

    private void tm4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm4MouseEntered


        if(t.tm4.t.estrellas == 0){
            p_tm4.removeAll();
            JLabel l = new JLabel("Sin estrellas!");
            p_tm4.add(l);
        }
        if(t.tm4.t.estrellas == 3){
            p_tm4.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            star_3.setIcon(star1_icon);
            p_tm4.add(star_1); p_tm4.add(star_2); p_tm4.add(star_3);
        }
        if(t.tm4.t.estrellas == 2){
            p_tm4.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            p_tm4.add(star_1); p_tm4.add(star_2); 
        }
        if(t.tm4.t.estrellas == 1){
            p_tm4.removeAll();
            star_1.setIcon(star1_icon);
            p_tm4.add(star_1);
        }
        j_tm4.setTitle("Estrellas TM1");
        j_tm4.add(p_tm4);
        j_tm4.setBounds(340,200,100,100);
        j_tm4.setLocationRelativeTo(null);        j_tm4.setVisible(true);
    }//GEN-LAST:event_tm4MouseEntered

    private void tm4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm4MouseExited
        j_tm4.setVisible(false);
    }//GEN-LAST:event_tm4MouseExited

    private void tm5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm5MouseEntered
        if(t.tm5.t.estrellas == 0){
            p_tm5.removeAll();
            JLabel l = new JLabel("Sin estrellas!");
            p_tm5.add(l);
        }
        if(t.tm5.t.estrellas == 3){
            p_tm5.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            star_3.setIcon(star1_icon);
            p_tm5.add(star_1); p_tm5.add(star_2); p_tm5.add(star_3);
        }
        if(t.tm5.t.estrellas == 2){
            p_tm5.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            p_tm5.add(star_1); p_tm5.add(star_2); 
        }
        if(t.tm5.t.estrellas == 1){
            p_tm5.removeAll();
            star_1.setIcon(star1_icon);
            p_tm5.add(star_1);
        }
        j_tm5.setTitle("Estrellas TM1");
        j_tm5.add(p_tm5);
        j_tm5.setBounds(340,200,100,100);
        j_tm5.setLocationRelativeTo(null);        j_tm5.setVisible(true);
    }//GEN-LAST:event_tm5MouseEntered

    private void tm5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm5MouseExited
        j_tm5.setVisible(false);
    }//GEN-LAST:event_tm5MouseExited

    private void ta1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta1MouseEntered
        if(t.ta1.t.estrellas == 0){
            p_ta1.removeAll();
            JLabel l = new JLabel("Sin estrellas!");
            p_ta1.add(l);
        }
        if(t.ta1.t.estrellas == 3){
            p_ta1.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            star_3.setIcon(star1_icon);
            p_ta1.add(star_1); p_ta1.add(star_2); p_ta1.add(star_3);
        }
        if(t.ta1.t.estrellas == 2){
            p_ta1.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            p_ta1.add(star_1); p_ta1.add(star_2); 
        }
        if(t.ta1.t.estrellas == 1){
            p_ta1.removeAll();
            star_1.setIcon(star1_icon);
            p_ta1.add(star_1);
        }
        j_ta1.setTitle("Estrellas TM1");
        j_ta1.add(p_ta1);
        j_ta1.setBounds(340,200,100,100);
        j_ta1.setLocationRelativeTo(null);        j_ta1.setVisible(true);
    }//GEN-LAST:event_ta1MouseEntered

    private void ta3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta3MouseEntered
        if(t.ta3.t.estrellas == 0){
            p_ta3.removeAll();
            JLabel l = new JLabel("Sin estrellas!");
            p_ta3.add(l);
        }
        if(t.ta3.t.estrellas == 3){
            p_ta3.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            star_3.setIcon(star1_icon);
            p_ta3.add(star_1); p_ta3.add(star_2); p_ta3.add(star_3);
        }
        if(t.ta3.t.estrellas == 2){
            p_ta3.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            p_ta3.add(star_1); p_ta3.add(star_2); 
        }
        if(t.ta3.t.estrellas == 1){
            p_ta3.removeAll();
            star_1.setIcon(star1_icon);
            p_ta3.add(star_1);
        }
        j_ta3.setTitle("Estrellas TM1");
        j_ta3.add(p_ta3);
        j_ta3.setBounds(340,200,100,100);
        j_ta3.setLocationRelativeTo(null);        j_ta3.setVisible(true);
    }//GEN-LAST:event_ta3MouseEntered

    private void ta3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta3MouseExited
       j_ta3.setVisible(false);
    }//GEN-LAST:event_ta3MouseExited

    private void ta4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta4MouseEntered
        if(t.ta4.t.estrellas == 0){
            p_ta4.removeAll();
            JLabel l = new JLabel("Sin estrellas!");
            p_ta4.add(l);
        }
        if(t.ta4.t.estrellas == 3){
            p_ta4.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            star_3.setIcon(star1_icon);
            p_ta4.add(star_1); p_ta4.add(star_2); p_ta4.add(star_3);
        }
        if(t.ta4.t.estrellas == 2){
            p_ta4.removeAll();
            star_1.setIcon(star1_icon);
            star_2.setIcon(star1_icon);
            p_ta4.add(star_1); p_ta4.add(star_2); 
        }
        if(t.ta4.t.estrellas == 1){
            p_ta4.removeAll();
            star_1.setIcon(star1_icon);
            p_ta4.add(star_1);
        }
        j_ta4.setTitle("Estrellas TM1");
        j_ta4.add(p_ta4);
        j_ta4.setBounds(340,200,100,100);
        j_ta4.setLocationRelativeTo(null);        j_ta4.setVisible(true);
    }//GEN-LAST:event_ta4MouseEntered

    private void ta4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta4MouseExited
        j_ta4.setVisible(false);
    }//GEN-LAST:event_ta4MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        HistorialUsuarios h = new HistorialUsuarios();
        h.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/icono_reflejo.png")));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/icono.png")));
    }//GEN-LAST:event_jLabel1MouseExited

    private void datos_usuario1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datos_usuario1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_datos_usuario1MouseEntered

    private void datos_usuario1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datos_usuario1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_datos_usuario1PropertyChange

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        u.progresoUsuario();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        u.escribirUsuario(u);
    }//GEN-LAST:event_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JLabel datos_usuario;
    private javax.swing.JLabel datos_usuario1;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton ta1;
    private javax.swing.JButton ta2;
    private javax.swing.JButton ta3;
    private javax.swing.JButton ta4;
    private javax.swing.JButton tb1;
    private javax.swing.JButton tb2;
    private javax.swing.JButton tb3;
    private javax.swing.JButton tb4;
    private javax.swing.JButton tb5;
    private javax.swing.JButton tm1;
    private javax.swing.JButton tm2;
    private javax.swing.JButton tm3;
    private javax.swing.JButton tm4;
    private javax.swing.JButton tm5;
    // End of variables declaration//GEN-END:variables
}
