/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopoo;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static proyectopoo.PantallaPrincipal.u;
/**
 *
 * @author irvin
 */
public class NivelInicial extends javax.swing.JFrame {

    /**
     * Creates new form NivelInicial
     */
    public NivelInicial() {
        initComponents();
    }
    public static Repertorio_Musica r = new Repertorio_Musica();
    public static Tacticas t = new Tacticas();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tb1 = new javax.swing.JButton();
        tm2 = new javax.swing.JButton();
        ta3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/icono.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 310, 410));

        tb1.setText("1");
        tb1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tb1MouseMoved(evt);
            }
        });
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb1MouseExited(evt);
            }
        });
        tb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb1ActionPerformed(evt);
            }
        });
        getContentPane().add(tb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 100, 60));

        tm2.setText("2");
        tm2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tm2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tm2MouseExited(evt);
            }
        });
        tm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tm2ActionPerformed(evt);
            }
        });
        getContentPane().add(tm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 90, 60));

        ta3.setText("3");
        ta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ta3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ta3MouseExited(evt);
            }
        });
        ta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ta3ActionPerformed(evt);
            }
        });
        getContentPane().add(ta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 90, 60));

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel3.setText("<html><font color='white'>Vamos a calcular tu nivel inicial!</font></html>");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 40));

        jButton1.setText("Calcula mi nivel!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/fondo_resize.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 410));

        jLabel4.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel3.setText("<html><font color='white'>Vamos a calcular tu nivel inicial!</font></html>");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tb1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseMoved

    }//GEN-LAST:event_tb1MouseMoved

    boolean realizado1 = false, realizado2 = false, realizado3 = false;
    int aciertos = 0;
    private void tb1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseEntered

    }//GEN-LAST:event_tb1MouseEntered

    private void tb1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_tb1MouseExited

    private void tb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb1ActionPerformed
        if(realizado1 == false){
            t.tb1.t.intentos = 0; t.tb1.t.pieza_activa = null; t.tb1.t.victoria = false;
            t.tb1.t.initGrid();t.tb1.t.drawBoard();
            t.tb1.run();
            realizado1 = true;    
        }
        else{
            JLabel l = new JLabel();
            JFrame f = new JFrame();
            f.setTitle("XD");
            f.setBounds(10,10,300,150);
            f.setLocationRelativeTo(null);
            l.setText("Ya intentaste esta tactica!");
            f.add(l);
            f.setVisible(true);
        }

        

    }//GEN-LAST:event_tb1ActionPerformed

    private void tm2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm2MouseEntered

    }//GEN-LAST:event_tm2MouseEntered

    private void tm2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm2MouseExited

    }//GEN-LAST:event_tm2MouseExited

    private void tm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tm2ActionPerformed
        if(realizado2 == false){
            t.tm2.t.intentos = 0; t.tm2.t.pieza_activa = null; t.tm2.t.victoria = false;
            t.tm2.t.initGrid();t.tb1.t.drawBoard();
            t.tm2.run();
            realizado2 = true;    
        }
        else{
            JLabel l = new JLabel();
            JFrame f = new JFrame();
            f.setTitle("Aviso!");
            f.setBounds(10,10,300,150);
            f.setLocationRelativeTo(null);
            l.setText("Ya intentaste esta tactica!");
            f.add(l);
            f.setVisible(true);
        }
    }//GEN-LAST:event_tm2ActionPerformed

    private void ta3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta3MouseEntered

    }//GEN-LAST:event_ta3MouseEntered

    private void ta3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta3MouseExited

    }//GEN-LAST:event_ta3MouseExited

    private void ta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ta3ActionPerformed
        if(realizado3 == false){
            t.ta3.t.intentos = 0; t.ta3.t.pieza_activa = null; t.ta3.t.victoria = false;
            t.ta3.t.initGrid();t.tb1.t.drawBoard();
            t.ta3.run();
            realizado3 = true;    
        }
        else{
            JLabel l = new JLabel();
            JFrame f = new JFrame();
            f.setTitle("Aviso!");
            f.setBounds(10,10,300,150);
            f.setLocationRelativeTo(null);
            l.setText("Ya intentaste esta tactica!");
            f.add(l);
            f.setVisible(true);
        }
    }//GEN-LAST:event_ta3ActionPerformed
    JLabel l = new JLabel();
    JFrame f = new JFrame();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(realizado1) aciertos ++;
        if(realizado2) aciertos++;
        if(realizado3) aciertos++;
        f.setTitle("Nivel inicial!");
        f.setBounds(10,10,300,150);
        f.setLocationRelativeTo(null);
        if(aciertos == 3){
            l.setText("Tu ELO inicial es de 2000!");
            f.add(l);
            f.setVisible(true);
            u.setElo(2000);
        }
        if(aciertos == 2){
            l.setText("Tu ELO inicial es de 1600!");
            f.add(l);
            f.setVisible(true);
            u.setElo(1600);
        }      
        if(aciertos == 1){
            l.setText("Tu ELO inicial es de 1200!");
            f.add(l);
            f.setVisible(true); u.setElo(1200);
        }  
        if(aciertos == 0){
            l.setText("Tu ELO inicial es de 800!");
            f.add(l);
            f.setVisible(true); u.setElo(800);
        }  
        dispose();
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/icono_reflejo.png")));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/icono.png")));
    }//GEN-LAST:event_jLabel1MouseExited
    

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivelInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivelInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivelInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivelInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NivelInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton ta3;
    private javax.swing.JButton tb1;
    private javax.swing.JButton tm2;
    // End of variables declaration//GEN-END:variables
}
