/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopoo;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.*;


/**
 *
 * @author irvin
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    public static Usuario u = new Usuario();

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    public Usuario getUsuario(){return u;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAnadir = new javax.swing.JButton();
        entradanombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tácticas!");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("<html><font color='white'>Nombre:</font></html>");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 40));

        jLabel5.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel5.setText("<html><font color='white'>Bienvenido al programa de tacticas de ajedrez!</font></html>");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 30));

        btnAnadir.setText("Aceptar");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 80, -1));

        entradanombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradanombreActionPerformed(evt);
            }
        });
        entradanombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                entradanombreKeyPressed(evt);
            }
        });
        getContentPane().add(entradanombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 310, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/fondo_resize.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/icono.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 310, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        // TODO add your handling code here:
        if(!nombre.equals("")){
            System.out.println("El nombre es:"+nombre);
            u.setNombre(nombre);
            dispose();
            NivelInicial i = new NivelInicial();
            i.setVisible(true);
        }
        else{
            JLabel l = new JLabel("XD");
            l.setText("Debe ingresar al menos 1 caracter!");
            JFrame j = new JFrame();
            j.setTitle(":/");
            j.add(l);
            j.setSize(250,100);
            j.setLocationRelativeTo(null);
            j.setResizable(false);
            j.setVisible(true);
            
        }


    }//GEN-LAST:event_btnAnadirActionPerformed

    private void entradanombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradanombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_entradanombreActionPerformed
    String nombre = "";
    private void entradanombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entradanombreKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()>='a'&&evt.getKeyChar()<='z'||evt.getKeyChar()>='A'&&evt.getKeyChar()<='Z'){
            
            nombre += evt.getKeyChar();
            System.out.println(evt.getKeyChar());
            evt.consume();       
        }
        else{
            JOptionPane.showMessageDialog(null, "Solo se permiten nombres con mayusculas y minusculas","Info importante XD",JOptionPane.INFORMATION_MESSAGE);
            entradanombre.setText(nombre);//Se regresa al instante antes de poner el caracteri ilegal
        }
    }//GEN-LAST:event_entradanombreKeyPressed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/icono_reflejo.png")));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/icono.png")));
    }//GEN-LAST:event_jLabel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new PantallaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JTextField entradanombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
